// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPPContractManagement.API.Data;

#nullable disable

namespace NPPContractManagement.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250923181058_UpdateContractVersionsSchema")]
    partial class UpdateContractVersionsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NPPContractManagement.API.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ForeignContractId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("SendToPerformance")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SuspendedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Terms")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractNumber")
                        .IsUnique();

                    b.HasIndex("DistributorId");

                    b.HasIndex("IndustryId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractNumber = "CNT-2025-001",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            Description = "Comprehensive food service contract for university dining facilities",
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IndustryId = 1,
                            IsSuspended = false,
                            ManufacturerId = 1,
                            Name = "",
                            SendToPerformance = true,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            Title = "University Food Service Contract 2025",
                            TotalValue = 500000.00m
                        },
                        new
                        {
                            Id = 2,
                            ContractNumber = "CNT-2025-002",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            Description = "Food service agreement for K-12 school district cafeterias",
                            EndDate = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IndustryId = 2,
                            IsSuspended = false,
                            ManufacturerId = 2,
                            Name = "",
                            SendToPerformance = true,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            Title = "K-12 School District Agreement",
                            TotalValue = 750000.00m
                        },
                        new
                        {
                            Id = 3,
                            ContractNumber = "CNT-2025-003",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            Description = "Food service contract for healthcare facilities and hospitals",
                            EndDate = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IndustryId = 4,
                            IsSuspended = false,
                            ManufacturerId = 3,
                            Name = "",
                            SendToPerformance = false,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            Title = "Healthcare Facilities Contract",
                            TotalValue = 300000.00m
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractDistributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.HasIndex("ContractId", "DistributorId")
                        .IsUnique();

                    b.ToTable("ContractDistributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            DistributorId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            DistributorId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            DistributorId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            DistributorId = 3,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractIndustry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("ContractId", "IndustryId")
                        .IsUnique();

                    b.ToTable("ContractIndustries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            IndustryId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            IndustryId = 2,
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            IndustryId = 4,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ContractId", "ManufacturerId")
                        .IsUnique();

                    b.ToTable("ContractManufacturers");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractOpCo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OpCoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpCoId");

                    b.HasIndex("ContractId", "OpCoId")
                        .IsUnique();

                    b.ToTable("ContractOpCos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            IsActive = true,
                            OpCoId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            IsActive = true,
                            OpCoId = 4
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            IsActive = true,
                            OpCoId = 2
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVersionNumber = 1,
                            IsActive = true,
                            OpCoId = 3
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<decimal>("ContractPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MaximumQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ProductId");

                    b.ToTable("ContractProducts");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ForeignContractId")
                        .HasColumnType("longtext");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("SendToPerformance")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SuspendedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ContractVersions");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractVersionPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PriceType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UOM")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContractVersionId");

                    b.HasIndex("ProductId");

                    b.ToTable("ContractVersionPrices");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.CustomerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Association")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CombinedUniqueID")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerAccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("DSO")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateToEntegra")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Markup")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MemberAccountId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OpCoId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SalesRep")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TRACSAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ToEntegra")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MemberAccountId");

                    b.HasIndex("OpCoId");

                    b.HasIndex("DistributorId", "CustomerAccountNumber")
                        .IsUnique();

                    b.ToTable("CustomerAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "5801 S Ellis Ave, Chicago, IL 60637",
                            Association = 1,
                            City = "Chicago",
                            ContactPerson = "Jennifer Adams",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditLimit = 50000.00m,
                            CurrentBalance = 12500.00m,
                            CustomerAccountNumber = "CUST001",
                            CustomerName = "UChicago Main Dining",
                            DistributorId = 1,
                            Email = "dining@uchicago.edu",
                            IsActive = true,
                            MemberAccountId = 1,
                            OpCoId = 1,
                            PhoneNumber = "(773) 702-1234",
                            State = "IL",
                            Status = 1,
                            TRACSAccess = false,
                            ToEntegra = false,
                            ZipCode = "60637"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 School St, Atlanta, GA 30309",
                            Association = 1,
                            City = "Atlanta",
                            ContactPerson = "Mary Johnson",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditLimit = 25000.00m,
                            CurrentBalance = 5000.00m,
                            CustomerAccountNumber = "CUST002",
                            CustomerName = "Lincoln School Cafeteria",
                            DistributorId = 2,
                            Email = "cafeteria@lincoln.edu",
                            IsActive = true,
                            MemberAccountId = 2,
                            OpCoId = 2,
                            PhoneNumber = "(404) 555-5000",
                            State = "GA",
                            Status = 1,
                            TRACSAccess = false,
                            ToEntegra = false,
                            ZipCode = "30309"
                        },
                        new
                        {
                            Id = 3,
                            Address = "456 Fast Food Blvd, Dallas, TX 75201",
                            Association = 1,
                            City = "Dallas",
                            ContactPerson = "Carlos Rodriguez",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditLimit = 15000.00m,
                            CurrentBalance = 3200.00m,
                            CustomerAccountNumber = "CUST003",
                            CustomerName = "Quick Bite Main Location",
                            DistributorId = 3,
                            Email = "manager@quickbite.com",
                            IsActive = true,
                            MemberAccountId = 3,
                            OpCoId = 3,
                            PhoneNumber = "(214) 555-6000",
                            State = "TX",
                            Status = 1,
                            TRACSAccess = false,
                            ToEntegra = false,
                            ZipCode = "75201"
                        },
                        new
                        {
                            Id = 4,
                            Address = "789 Health Way, Chicago, IL 60611",
                            Association = 1,
                            City = "Chicago",
                            ContactPerson = "Dr. Patricia Lee",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreditLimit = 75000.00m,
                            CurrentBalance = 18750.00m,
                            CustomerAccountNumber = "CUST004",
                            CustomerName = "General Hospital Food Service",
                            DistributorId = 1,
                            Email = "food@generalhospital.org",
                            IsActive = true,
                            MemberAccountId = 4,
                            OpCoId = 4,
                            PhoneNumber = "(312) 555-7000",
                            State = "IL",
                            Status = 1,
                            TRACSAccess = false,
                            ToEntegra = false,
                            ZipCode = "60611"
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("ReceiveContractProposal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Distributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Distribution Way, Chicago, IL 60601",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Regional Food Services",
                            PhoneNumber = "(312) 555-0100",
                            ReceiveContractProposal = true,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Supply Chain Blvd, Atlanta, GA 30309",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Metro Food Distribution",
                            PhoneNumber = "(404) 555-0200",
                            ReceiveContractProposal = true,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Logistics Ave, Dallas, TX 75201",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "National Food Partners",
                            PhoneNumber = "(214) 555-0300",
                            ReceiveContractProposal = false,
                            Status = 1
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.DistributorProductCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CatchWeight")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DistributorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DistributorPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("EBrand")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("DistributorId", "DistributorCode")
                        .IsUnique();

                    b.HasIndex("DistributorId", "ProductId")
                        .IsUnique();

                    b.ToTable("DistributorProductCodes");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Higher education institutions",
                            IsActive = true,
                            Name = "College & University",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Primary and secondary education",
                            IsActive = true,
                            Name = "K-12",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast food and quick service restaurants",
                            IsActive = true,
                            Name = "Quick Serve Restaurant",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hospitals and healthcare facilities",
                            IsActive = true,
                            Name = "Healthcare",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Corporate dining and cafeterias",
                            IsActive = true,
                            Name = "Corporate",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AKA")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PrimaryBroker")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AKA = "Sysco",
                            Address = "1390 Enclave Pkwy, Houston, TX 77077",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sysco Corporation",
                            PhoneNumber = "(281) 584-1390",
                            PrimaryBroker = "John Smith",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AKA = "USF",
                            Address = "9399 W Higgins Rd, Rosemont, IL 60018",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "US Foods",
                            PhoneNumber = "(847) 720-8000",
                            PrimaryBroker = "Jane Doe",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AKA = "PFG",
                            Address = "12500 West Creek Pkwy, Richmond, VA 23238",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Performance Food Group",
                            PhoneNumber = "(804) 484-7700",
                            PrimaryBroker = "Mike Johnson",
                            Status = 1
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.MemberAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("AuditDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("ClientGroupEnrollment")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClientGroupNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EntegraGPONumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntegraIdNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LopDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MemberNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParentMemberAccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PayType")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SalesforceAccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxId")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("VMAPNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VMSupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("VMSupplierSite")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("W9")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("MemberNumber")
                        .IsUnique();

                    b.ToTable("MemberAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "5801 S Ellis Ave, Chicago, IL 60637",
                            BusinessType = "Educational Institution",
                            City = "Chicago",
                            ClientGroupEnrollment = false,
                            ContactPerson = "Jennifer Adams",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dining@uchicago.edu",
                            FacilityName = "University of Chicago Dining",
                            IndustryId = 1,
                            IsActive = true,
                            MemberNumber = "MEM001",
                            PayType = 1,
                            PhoneNumber = "(773) 702-1234",
                            SalesforceAccountName = "",
                            State = "IL",
                            Status = 1,
                            TaxId = "36-1234567",
                            W9 = true,
                            ZipCode = "60637"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 School St, Atlanta, GA 30309",
                            BusinessType = "Public School",
                            City = "Atlanta",
                            ClientGroupEnrollment = false,
                            ContactPerson = "Mary Johnson",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "cafeteria@lincoln.edu",
                            FacilityName = "Lincoln Elementary School",
                            IndustryId = 2,
                            IsActive = true,
                            MemberNumber = "MEM002",
                            PayType = 1,
                            PhoneNumber = "(404) 555-5000",
                            SalesforceAccountName = "",
                            State = "GA",
                            Status = 1,
                            TaxId = "58-9876543",
                            W9 = true,
                            ZipCode = "30309"
                        },
                        new
                        {
                            Id = 3,
                            Address = "456 Fast Food Blvd, Dallas, TX 75201",
                            BusinessType = "Restaurant",
                            City = "Dallas",
                            ClientGroupEnrollment = false,
                            ContactPerson = "Carlos Rodriguez",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@quickbite.com",
                            FacilityName = "Quick Bite Restaurant",
                            IndustryId = 3,
                            IsActive = true,
                            MemberNumber = "MEM003",
                            PayType = 1,
                            PhoneNumber = "(214) 555-6000",
                            SalesforceAccountName = "",
                            State = "TX",
                            Status = 1,
                            TaxId = "75-1122334",
                            W9 = false,
                            ZipCode = "75201"
                        },
                        new
                        {
                            Id = 4,
                            Address = "789 Health Way, Chicago, IL 60611",
                            BusinessType = "Healthcare Facility",
                            City = "Chicago",
                            ClientGroupEnrollment = false,
                            ContactPerson = "Dr. Patricia Lee",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "food@generalhospital.org",
                            FacilityName = "General Hospital Cafeteria",
                            IndustryId = 4,
                            IsActive = true,
                            MemberNumber = "MEM004",
                            PayType = 1,
                            PhoneNumber = "(312) 555-7000",
                            SalesforceAccountName = "",
                            State = "IL",
                            Status = 1,
                            TaxId = "36-5566778",
                            W9 = true,
                            ZipCode = "60611"
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.OpCo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RemoteReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("OpCos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 N Michigan Ave, Chicago, IL 60601",
                            City = "Chicago",
                            ContactPerson = "Sarah Wilson",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistributorId = 1,
                            Email = "chicago@regionalfood.com",
                            IsActive = true,
                            Name = "Chicago Operations",
                            PhoneNumber = "(312) 555-1001",
                            RemoteReferenceCode = "CHI001",
                            State = "IL",
                            Status = 1,
                            ZipCode = "60601"
                        },
                        new
                        {
                            Id = 2,
                            Address = "200 Peachtree St, Atlanta, GA 30303",
                            City = "Atlanta",
                            ContactPerson = "Robert Brown",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistributorId = 2,
                            Email = "atlanta@metrofood.com",
                            IsActive = true,
                            Name = "Atlanta Hub",
                            PhoneNumber = "(404) 555-2001",
                            RemoteReferenceCode = "ATL001",
                            State = "GA",
                            Status = 1,
                            ZipCode = "30303"
                        },
                        new
                        {
                            Id = 3,
                            Address = "300 Main St, Dallas, TX 75202",
                            City = "Dallas",
                            ContactPerson = "Lisa Garcia",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistributorId = 3,
                            Email = "dallas@nationalfood.com",
                            IsActive = true,
                            Name = "Dallas Center",
                            PhoneNumber = "(214) 555-3001",
                            RemoteReferenceCode = "DAL001",
                            State = "TX",
                            Status = 1,
                            ZipCode = "75202"
                        },
                        new
                        {
                            Id = 4,
                            Address = "400 W Lake St, Chicago, IL 60606",
                            City = "Chicago",
                            ContactPerson = "David Miller",
                            Country = "USA",
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistributorId = 1,
                            Email = "west@regionalfood.com",
                            IsActive = true,
                            Name = "Chicago West",
                            PhoneNumber = "(312) 555-1002",
                            RemoteReferenceCode = "CHI002",
                            State = "IL",
                            Status = 1,
                            ZipCode = "60606"
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GTIN")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("ManufacturerProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PackSize")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UPC")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Meat",
                            CostPrice = 38.50m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium Ground Beef 80/20",
                            GTIN = "1234567890123",
                            IsActive = true,
                            ListPrice = 45.99m,
                            ManufacturerId = 1,
                            ManufacturerProductCode = "SYSCO-BEEF-001",
                            Name = "",
                            PackSize = "10 lb",
                            SKU = "SYS001",
                            Status = 1,
                            SubCategory = "Ground Beef",
                            UPC = "123456789012"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Meat",
                            CostPrice = 27.50m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Boneless Chicken Breast",
                            GTIN = "2345678901234",
                            IsActive = true,
                            ListPrice = 32.99m,
                            ManufacturerId = 2,
                            ManufacturerProductCode = "USF-CHICKEN-001",
                            Name = "",
                            PackSize = "5 lb",
                            SKU = "USF001",
                            Status = 1,
                            SubCategory = "Chicken",
                            UPC = "234567890123"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Produce",
                            CostPrice = 15.25m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh Romaine Lettuce",
                            GTIN = "3456789012345",
                            IsActive = true,
                            ListPrice = 18.99m,
                            ManufacturerId = 3,
                            ManufacturerProductCode = "PFG-PRODUCE-001",
                            Name = "",
                            PackSize = "24 count",
                            SKU = "PFG001",
                            Status = 1,
                            SubCategory = "Lettuce",
                            UPC = "345678901234"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Dairy",
                            CostPrice = 10.75m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Whole Milk Gallon",
                            GTIN = "4567890123456",
                            IsActive = true,
                            ListPrice = 12.99m,
                            ManufacturerId = 1,
                            ManufacturerProductCode = "SYSCO-DAIRY-001",
                            Name = "",
                            PackSize = "4 gallons",
                            SKU = "SYS002",
                            Status = 1,
                            SubCategory = "Milk",
                            UPC = "456789012345"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frozen",
                            CostPrice = 20.50m,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Frozen French Fries",
                            GTIN = "5678901234567",
                            IsActive = true,
                            ListPrice = 24.99m,
                            ManufacturerId = 2,
                            ManufacturerProductCode = "USF-FROZEN-001",
                            Name = "",
                            PackSize = "6/5 lb",
                            SKU = "USF002",
                            Status = 1,
                            SubCategory = "Potato Products",
                            UPC = "567890123456"
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            IsActive = true,
                            Name = "System Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage contracts and related data",
                            IsActive = true,
                            Name = "Contract Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manufacturer user access",
                            IsActive = true,
                            Name = "Manufacturer"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Distributor user access",
                            IsActive = true,
                            Name = "Distributor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read-only access",
                            IsActive = true,
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Class")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FailedAuthAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IndustryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("UserManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("NOW(6)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("UserId");

                    b.ToTable("UserManufacturers", (string)null);
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Contract", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Distributor", null)
                        .WithMany("Contracts")
                        .HasForeignKey("DistributorId");

                    b.HasOne("NPPContractManagement.API.Models.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractDistributor", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Contract", "Contract")
                        .WithMany("ContractDistributors")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractIndustry", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Contract", "Contract")
                        .WithMany("ContractIndustries")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.Industry", "Industry")
                        .WithMany("ContractIndustries")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractManufacturer", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractOpCo", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Contract", "Contract")
                        .WithMany("ContractOpCos")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.OpCo", "OpCo")
                        .WithMany("ContractOpCos")
                        .HasForeignKey("OpCoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("OpCo");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractProduct", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Contract", "Contract")
                        .WithMany("ContractProducts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.Product", "Product")
                        .WithMany("ContractProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractVersion", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Contract", "Contract")
                        .WithMany("ContractVersions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractVersionPrice", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.ContractVersion", "ContractVersion")
                        .WithMany("Prices")
                        .HasForeignKey("ContractVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractVersion");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.CustomerAccount", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Distributor", "Distributor")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.MemberAccount", "MemberAccount")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("MemberAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.OpCo", "OpCo")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("OpCoId");

                    b.Navigation("Distributor");

                    b.Navigation("MemberAccount");

                    b.Navigation("OpCo");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.DistributorProductCode", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.Product", "Product")
                        .WithMany("DistributorProductCodes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.MemberAccount", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Industry", "Industry")
                        .WithMany("MemberAccounts")
                        .HasForeignKey("IndustryId");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.OpCo", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Distributor", "Distributor")
                        .WithMany("OpCos")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Product", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.User", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Industry", "Industry")
                        .WithMany("Users")
                        .HasForeignKey("IndustryId");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.UserRole", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManufacturers", b =>
                {
                    b.HasOne("NPPContractManagement.API.Models.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NPPContractManagement.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Contract", b =>
                {
                    b.Navigation("ContractDistributors");

                    b.Navigation("ContractIndustries");

                    b.Navigation("ContractOpCos");

                    b.Navigation("ContractProducts");

                    b.Navigation("ContractVersions");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.ContractVersion", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Distributor", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("CustomerAccounts");

                    b.Navigation("OpCos");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Industry", b =>
                {
                    b.Navigation("ContractIndustries");

                    b.Navigation("MemberAccounts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Manufacturer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.MemberAccount", b =>
                {
                    b.Navigation("CustomerAccounts");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.OpCo", b =>
                {
                    b.Navigation("ContractOpCos");

                    b.Navigation("CustomerAccounts");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Product", b =>
                {
                    b.Navigation("ContractProducts");

                    b.Navigation("DistributorProductCodes");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NPPContractManagement.API.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
